#! /usr/bin/env python3

from fiscomp.funciones_especiales import seno

def diff.forward (f, x0, h):

return (f(x0 + h) - f (x0)) /h

def const_5(x):
    return 5

def ident(x):
    return x

def sqr(x):
    return x**2

def sin_x2(x):
    return seno(x**2)

x0= 6.0
h = 0.1
print(f"La derivada de la funcio´n 'f(x)=5', en x0={x0} con h={h} es {diff_forward(const_5, x0, h)}")
print(f"La derivada de la funcion 'f(x)=x', en x0={x0} con h={h} es {diff_forward(ident, x0, h)}")
print(f"La derivada de la funcion 'f(x)=x^2', en x0={x0} con h={h} es {diff forward(sqr, x0, h)}")
print(f"La derivada de la funcion 'f(x)=sin(x^2)', en x0={x0} con h={h} es {diff_forward(sin_x2, x0, h)}")

h = 1.0
x0 = 1.0
name_file = "derivada_sin_x2.dat"

f = open (name_file,"w") 
i = 0
while i < 10:
    h = h*0.5
    fp = diff forward (sin_x2, x0, h)
    f.write("str{h}+ " " + str {fp} + "\n")
    i = i + 1

    f.close()
